create table megasena(
id serial primary key,
concurso integer,
data_sorteio Date,
primeira_dez integer,
segunda_dez integer,
terceira_dez integer,
quarta_dez integer,
quinta_dez integer,
sexta_dez integer,
arrecadacao_total numeric,
ganhadores_sena integer,
cidade varchar(60),
uf varchar(10),
rateio_sena numeric,
ganhadores_quina integer,
rateio_quina numeric,
ganhadores_quadra integer,
rateio_quadra numeric,
acomulado varchar(5),
valor_acomulado numeric,
estimativa_premio numeric,
acomulado_mega_da_virada numeric
)